/**
 * All known npm packages.
 */
export enum NpmPackage {
    TAILWIND = 'tailwindcss',
    NGX_PERSISTENCE_LOGGER = 'ngx-persistence-logger',
    NGX_MATERIAL_AUTH = 'ngx-material-auth',
    NGX_MATERIAL_CHANGE_SETS = 'ngx-material-change-sets',
    NGX_MATERIAL_TRACKING = 'ngx-material-tracking',
    NGX_MATERIAL_NAVIGATION = 'ngx-material-navigation',
    NGX_MATERIAL_ENTITY = 'ngx-material-entity',
    NGX_PWA = 'ngx-pwa',
    TYPESCRIPT = 'typescript',
    ESLINT_CONFIG_SERVICE_SOFT = 'eslint-config-service-soft',
    ESLINT = 'eslint',
    POSTCSS = 'postcss',
    AUTOPREFIXER = 'autoprefixer',
    VITE_PLUGIN_DTS = 'vite-plugin-dts',
    LBX_JWT = 'lbx-jwt',
    LBX_CHANGE_SETS = 'lbx-change-sets',
    LBX_PERSISTENCE_LOGGER = 'lbx-persistence-logger',
    LOOPBACK_AUTHENTICATION = '@loopback/authentication',
    LOOPBACK_AUTHORIZATION = '@loopback/authorization',
    LOOPBACK_CRON = '@loopback/cron',
    LOOPBACK_CONNECTOR_POSTGRES = 'loopback-connector-postgresql',
    NODEMAILER_TYPES = '@types/nodemailer',
    LODASH = 'lodash',
    LODASH_TYPES = '@types/lodash',
    TSC_WATCH = 'tsc-watch',
    NG_PACKAGR = 'ng-packagr',
    TSLIB = 'tslib',
    LOOPBACK_4_MIGRATION = 'loopback4-migration',
    CLASS_VALIDATOR = 'class-validator',
    CLASS_TRANSFORMER = 'class-transformer',
    NEST_JS_SWAGGER = '@nestjs/swagger',
    NEST_JS_TYPEORM = '@nestjs/typeorm',
    TYPEORM = 'typeorm',
    PG = 'pg',
    MYSQL_2 = 'mysql2',
    // TODO: clean up after loopback4 bundling
    WEBPACK = 'webpack',
    WEBPACK_CLI = 'webpack-cli',
    TS_LOADER = 'ts-loader',
    WEBPACK_NODE_EXTERNALS = 'webpack-node-externals',
    TSCONFIG_PATH_WEBPACK_PLUGIN = 'tsconfig-paths-webpack-plugin',
    FORK_TS_CHECKER_WEBPACK_PLUGIN = 'fork-ts-checker-webpack-plugin',
    CLDRJS = 'cldrjs',
    CLDR_DATA = 'cldr-data',
    VITE = 'vite',
    VITE_TS_CONFIG_PATHS = 'vite-tsconfig-paths'
}