/**
 * All commands that the cli supports.
 */
export enum Command {
    HELP = 'help',
    H = 'h',
    VERSION = 'version',
    V = 'v',
    INIT = 'init',
    I = 'i',
    ADD = 'add',
    A = 'a',
    PREPARE = 'prepare',
    P = 'p',
    UP = 'up',
    U = 'u',
    DOWN = 'down',
    D = 'd',
    UP_DEV = 'up-dev',
    UD = 'ud',
    DOWN_DEV = 'down-dev',
    DD = 'dd',
    UP_LOCAL = 'up-local',
    UL = 'ul',
    DOWN_LOCAL = 'down-local',
    DL = 'dl',
    GENERATE_PAGE = 'generatePage',
    GP = 'gp',
    RUN_ALL = 'run-all',
    RUN_MANY = 'run-many',
    RA = 'ra',
    LIST = 'list',
    LS = 'ls',
    LIST_ALL = 'list-all',
    LA = 'la'
}